name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an idea for agents-flow.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What you would like to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Alternatives you've considered and why they don't work.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, mockups, or examples.
