name: Formatting

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run format
        run: npm run format:check
